version: '3'

services:
  app:
    build: .
    volumes:
      - .:/app
    user: root
    depends_on:
      - db
    command: /bin/sh -c "yarn start:dev"
    ports:
      - "3000:3000"
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: "/var/lib/postgresql/data/pgdata"

volumes:
  domain-db:
